require 'singularitygs'
require 'compass-normalize'
require 'breakpoint'

sass_dir = 'app/styles'
css_dir = '.tmp/styles'
generated_images_dir = '.tmp/images/generated'
images_dir = 'app/images'
javascripts_dir = 'app/scripts'
fonts_dir = 'app/styles/fonts'
import_path = 'app/bower_components'
http_images_path = '/images'
http_generated_images_path = '/images/generated'
http_fonts_path = '/styles/fonts'
relative_assets = false
