source 'https://rubygems.org'
gem 'sass', '~>3.3.0'
gem 'compass', :git => 'https://github.com/chriseppstein/compass.git', :branch => 'master'
gem 'compass-normalize', '1.4.3'
gem 'singularitygs', '1.2.0'
gem 'font-awesome-sass'
